___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [3]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [4]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [7]:
arr

array([10, 20, 30])

In [8]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int32

In [9]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [10]:
d

{'a': 10, 'b': 20, 'c': 30}

In [11]:
pd.Series(d)  # keyleri index, value leri seri olarak aldi

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(d, index=["q","c","y"])   #dict'in indexi oldugu icin sadece eslesenleri verdi
                                    # NaN larin data tipi floattir ***

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [14]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [15]:
pd.Series(data="Ahmet", index=range(1,5))

1    Ahmet
2    Ahmet
3    Ahmet
4    Ahmet
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [18]:
set1 = {1,2,3,6}

In [20]:
 # pd.Series(set1) set ile olmaz indexlenemez

In [21]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [22]:
pd.Series([set, list, dict])[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [39]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [24]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [25]:
pd.Series([sum, print, len])[0]([3,5,7])

15

In [29]:
mix_data = ['Aziz', 2, True]


In [31]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [32]:
type(ser)

pandas.core.series.Series

In [37]:
type(ser[2])

bool

In [34]:
arr = np.array(mix_data)                          # arr olunca data tipini degistirdi     
arr

array(['Aziz', '2', 'True'], dtype='<U11')

In [38]:
type(arr[2])

numpy.str_

### Basic Attributes of Series

In [43]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    52
1    68
2    37
3    21
4    72
5    31
6    41
dtype: int32

In [44]:
ser.dtype

dtype('int32')

In [45]:
type(ser)

pandas.core.series.Series

In [46]:
ser.shape

(7,)

In [47]:
ser.size

7

In [48]:
len(ser)

7

In [49]:
ser.ndim

1

In [50]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [51]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [52]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [53]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [58]:
ser.keys

<bound method Series.keys of 0    52
1    68
2    37
3    21
4    72
5    31
6    41
dtype: int32>

In [56]:
ser.values

array([52, 68, 37, 21, 72, 31, 41])

In [61]:
ser.item

<bound method IndexOpsMixin.item of 0    52
1    68
2    37
3    21
4    72
5    31
6    41
dtype: int32>

In [62]:
list(ser.items())

[(0, 52), (1, 68), (2, 37), (3, 21), (4, 72), (5, 31), (6, 41)]

In [63]:
for index, value in ser.items():
    print(f"index: {index}, value: {value}")

index: 0, value: 52
index: 1, value: 68
index: 2, value: 37
index: 3, value: 21
index: 4, value: 72
index: 5, value: 31
index: 6, value: 41


In [65]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c     7
b     4
a    14
e    14
f    11
d     5
g     5
i    12
h    12
j    24
dtype: int32

In [66]:
ser.head()  # defaultu 5 tir

c     7
b     4
a    14
e    14
f    11
dtype: int32

In [67]:
ser.head(7)

c     7
b     4
a    14
e    14
f    11
d     5
g     5
dtype: int32

In [68]:
ser.tail()  # son 5'i getirir

d     5
g     5
i    12
h    12
j    24
dtype: int32

In [69]:
ser.sample()  # rastgele bir satir getirir

b    4
dtype: int32

In [70]:
ser.sample(3)  # rastgele 3 satir getirir

e    14
g     5
b     4
dtype: int32

In [71]:
ser.sort_index(ascending=True)

a    14
b     4
c     7
d     5
e    14
f    11
g     5
h    12
i    12
j    24
dtype: int32

In [72]:
ser.sort_values(ascending=True)

b     4
d     5
g     5
c     7
f    11
i    12
h    12
a    14
e    14
j    24
dtype: int32

In [73]:
ser.sort_values(ascending=False)

j    24
a    14
e    14
i    12
h    12
f    11
c     7
d     5
g     5
b     4
dtype: int32

In [74]:
ser.isin([5,9])   # dizinimizde 5 ve 9 varmi

c    False
b    False
a    False
e    False
f    False
d     True
g     True
i    False
h    False
j    False
dtype: bool

In [76]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [77]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [78]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [79]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [80]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [81]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [82]:
ser1[1]

2

In [83]:
ser1["Germany"]

2

In [84]:
ser1.Germany  # index string ise direk yazabliriz. Rakam ve bosluk olmamali

2

Operations are then also done based off of index:

In [86]:
ser1 + ser2  # ortak elemanlarin degerlerini toplar. seride NaNlar oldugu icin sonucu float verdi

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [87]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [88]:
ser3[0]

'a'

In [89]:
ser3[:2]

0    a
1    b
dtype: object

In [90]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [94]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [95]:
panser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

In [96]:
panser["terry" : "orion"] # str lerle indexleme yaparsak son elemanida dahil ediyor

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes and Some New Attributes

In [97]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [98]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [99]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [100]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [101]:
panser[["terry", "orion"]]

In [106]:
panser.item

<bound method IndexOpsMixin.item of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [107]:
panser.items

<bound method Series.items of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [108]:
panser.items()

In [102]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [109]:
"terry" in panser

True

In [112]:
"terry" in panser.index

True

In [110]:
"bob" in panser

False

In [111]:
200 in panser.values

True

In [114]:
panser.isin([200, 150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [116]:
panser["terry"] = 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [117]:
panser[panser > 100]

micheal    200
orion      150
dtype: int64

In [118]:
panser[panser > 100] = 175
panser

terry       90
micheal    175
orion      175
jason       99
dtype: int64